### ISSUE TITLE
csvguess.q generated loader files will not work under 3.6

### ISSUE THREAD

**Issue by eepgwde** [simongarland/csvguess#1]
I've been using csvguess.q with earlier versions of the Linux 32-bit community edition.

I discovered when I upgraded to 3.6 that existing loader files and newly generated ones fail with an error.

I can provide more details on request.

**Comment by simongarland** [comment]
please do, email me directly if you’re including sample scripts/data

**Comment by eepgwde** [comment]
Sorry, I didn't reply sooner. I checked out this repository. I used the my own trns.csv and the output of createtest.q. Same error on the bracket in the load.
I have no Q environment variables and invoke directly q as ~/q/l32/q

A fragment of my input CSV (renamed with .txt for GitHub)
[trns.csv.txt](https://github.com/simongarland/csvguess/files/3778536/trns.csv.txt)

I've attached my typescript.log 
[typescript.log](https://github.com/simongarland/csvguess/files/3778526/typescript.log)

And this is the loader it generates
[trns.load.q.txt](https://github.com/simongarland/csvguess/files/3778537/trns.load.q.txt)

Here's the error itself.

    KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
    l32/ 4()core 7978MB weaves n1 192.168.145.130 NONEXPIRE  
    
    '{
      [0]  /misc/build/0/csvguess/test.load.q:30: LOAD:{[file] POSTLOADALL POSTLOADEACH$[NOHEADER;flip LOADHDRS!LOADDEFN[]0:;LOADHDRS xcol LOADDEFN[]0:]..
                                                                                                                                                         ^
      [0]  (<load>)
    
      )\\
    
I may not get the chance again, but thanks for all your work with q/kdb+.

**Comment by simongarland** [comment]
thanks for the example

it’s an issue with kdb+ 3.6 (the output from -3! now honours the \c settings for functions, meaning
function string representations may be truncated). 

I’ll let you know when it’s resolved.

as a temporary workaround if you add the line:
\c 2000 2000
to the top of csvguess.q and rerun the loader generation your generated loader scripts will be fine

sorry for the bother 

/Simon

**Comment by eepgwde** [comment]
Thanks very much! I would never have found it myself.
That will do for me. All the best for the next release!
